#!/usr/bin/env bash
# Build a Twitch CDN-ready ZIP of the extension.
# Usage: bash twitch-extension/package.sh <version> --ebs-origin <https-origin> [--ebs-origin ...]
#        (current release: 1.2.0)
# Output: twitch-extension/twitch-extension-<version>.zip
#
# The EBS URL is read at runtime from Twitch.ext.configuration.global (set in the
# Twitch Extensions console). Since issue #164 the panel only calls it when its
# origin is one of the --ebs-origin values baked into the packaged ebs-origins.js,
# so a leaked extension secret cannot point every panel at another server.
# Production packages list only the production host; a test package may add the
# test host. Example:
#   bash twitch-extension/package.sh 1.3.0 --ebs-origin https://example.org

set -e

USAGE="Usage: package.sh <version> --ebs-origin <https-origin> [--ebs-origin ...]  (e.g. 1.2.0 --ebs-origin https://example.org)"
VERSION=${1:?"$USAGE"}
shift
# The version is written into ebs-origins.js as a JS string (EXT_BUILD, issue #180).
if [[ ! "$VERSION" =~ ^[0-9A-Za-z.+-]+$ ]]; then
    echo "ERROR: version may contain only letters, digits, dots, + and -, got \"$VERSION\"." >&2
    exit 1
fi
EBS_ORIGINS=()
while [ $# -gt 0 ]; do
    case "$1" in
        --ebs-origin)
            ORIGIN="${2:-}"
            if [[ ! "$ORIGIN" =~ ^https://[A-Za-z0-9.-]+(:[0-9]+)?$ ]]; then
                echo "ERROR: --ebs-origin needs an https origin with no path or trailing slash, got \"$ORIGIN\"." >&2
                exit 1
            fi
            EBS_ORIGINS+=("$ORIGIN")
            shift 2
            ;;
        *)
            echo "ERROR: unknown argument \"$1\". $USAGE" >&2
            exit 1
            ;;
    esac
done
if [ ${#EBS_ORIGINS[@]} -eq 0 ]; then
    echo "ERROR: at least one --ebs-origin is required. $USAGE" >&2
    exit 1
fi
OUT="twitch-extension-${VERSION}.zip"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Files to include (dev-harness and package.sh are excluded)
FILES=(
    panel.html
    panel.js
    config.html
    config.js
    live_config.html
    live_config.js
    extension.js
    ebs-origins.js
    extension.css
    fonts/BigShouldersText-VariableFont_wght.ttf
    fonts/BigShouldersText-OFL.txt
)

# Viewer-facing files (Twitch policy 4.5, issue #157): no login, link-code,
# registration or website call-to-action. config.html and live_config.* are
# broadcaster-only and are not checked.
VIEWER_FILES=(panel.html panel.js extension.js extension.css)
FORBIDDEN_TEXT=("kana-cards.com" "Log into" "Generate Twitch Code" "Link your account")

cd "$SCRIPT_DIR"

if [ -e "$SCRIPT_DIR/$OUT" ]; then
    echo "ERROR: $OUT already exists — bump the version." >&2
    exit 1
fi

# Every local src/href in a packaged HTML file must be in FILES.
for html in "${FILES[@]}"; do
    [[ "$html" == *.html ]] || continue
    for ref in $(grep -oE '(src|href)="[^"]+"' "$html" | cut -d'"' -f2 | grep -vE '^((https?:)?//|#|data:|mailto:)'); do
        if ! printf '%s\n' "${FILES[@]}" | grep -qxF "$ref"; then
            echo "ERROR: $html references $ref, which is not packaged." >&2
            exit 1
        fi
    done
done

# Video component files, if any, are viewer-facing too.
for f in video*.html video*.js video*.css; do
    if [ -e "$f" ]; then VIEWER_FILES+=("$f"); fi
done

for f in "${VIEWER_FILES[@]}"; do
    for phrase in "${FORBIDDEN_TEXT[@]}"; do
        if grep -qiF -- "$phrase" "$f"; then
            echo "ERROR: viewer file $f contains forbidden text \"$phrase\" (Twitch policy 4.5: no outside call-to-action)." >&2
            exit 1
        fi
    done
    if grep -qiE 'type="?password' "$f"; then
        echo "ERROR: viewer file $f contains a password field." >&2
        exit 1
    fi
done

echo "Packaging extension v${VERSION}..."
# Stage a copy so the generated ebs-origins.js never overwrites the repository's.
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT
for f in "${FILES[@]}"; do
    mkdir -p "$STAGE/$(dirname "$f")"
    cp "$f" "$STAGE/$f"
done
ORIGINS_JS="["
SEP=""
for o in "${EBS_ORIGINS[@]}"; do
    ORIGINS_JS+="${SEP}\"${o}\""
    SEP=", "
done
ORIGINS_JS+="]"
EXT_BUILD_JS="var EXT_BUILD = {version: \"${VERSION}\", origins: ${ORIGINS_JS}};"
{
    echo "// Generated by package.sh v${VERSION} (issues #164, #180). Do not edit."
    echo "var EBS_ALLOWED_ORIGINS = ${ORIGINS_JS};"
    echo "$EXT_BUILD_JS"
} > "$STAGE/ebs-origins.js"
(cd "$STAGE" && zip "$SCRIPT_DIR/$OUT" "${FILES[@]}" > /dev/null)

echo "Created: twitch-extension/$OUT"
echo ""
echo "Dev console → Version → Asset Hosting:"
echo "  Panel Viewer Path:  panel.html"
echo "  Config Path:        config.html"
echo "  Live Config Path:   live_config.html"
echo "Panel calls only these backend origins (ebs-origins.js):"
for o in "${EBS_ORIGINS[@]}"; do echo "  $o"; done
echo "Dev console → Version → Capabilities → Allowlist for URL Fetching Domains:"
for o in "${EBS_ORIGINS[@]}"; do echo "  $o"; done
echo "Team logos in the panel's team draw load from the logo host; without an image"
echo "allowlist entry for it the panel shows monograms instead."
echo "Upload the zip, move the version to Hosted Test, verify all three views, then submit."
echo "Build stamp (ebs-origins.js; the configuration page's Connection check shows it):"
echo "  $EXT_BUILD_JS"
